# Required packages
addons:
    apt:
        packages:
            - gcc-5

language: c
compiler: gcc
env: GCC_VERSION=5

# Run only on the master branch
branches:
    only:
        - master

# Build a test binary and run tests
script: make -C source test

